---
- name: Uninstall Nginx
  hosts: all  
  become: true  

  tasks:
    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped

    - name: Remove Nginx package
      apt:
        name: nginx
        state: absent

    - name: Remove Nginx configuration files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx/nginx.conf
        - /etc/nginx/sites-available/
        - /etc/nginx/sites-enabled/

    - name: Reload systemd
      command: systemctl daemon-reload
