# .github/workflows/deploy.yml
name: Deploy Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Set up SSH keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PEM_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo -e "Host your_target_machine_ip\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

    - name: Run Ansible playbook
      run: ansible-playbook -i inventory.ini nginx-install-playbook.yaml
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
